udp_to_ros2_bridge:  # Node name
  ros__parameters:
    communication:
      IP: 0.0.0.0   # Your UDP host IP
      port: 61557            # UDP port to listen on
    ros_topic: "tactile_sensors_from_udp"     # Topic name for publishing UDP messages